title: PyConf Hyderabad 2019
description: PyConf Hyderabad is an yearly tech conference about python, it's projects and development
mail: hydpy@example.com
twitter: hydpy
github: https://github.com/hydpy

baseurl: '/'

tickets_link: ""
schedule_link: ""

sass:
  sass_dir: _sass
  style: compressed
